version: "3.9"
services:

  vertica:
    environment:
      APP_DB_USER: "dbadmin"
      APP_DB_PASSWORD: ""
      TZ: "Etc/UTC"
    image: vertica/vertica-ce
    ports:
      - "5433:5433"
      - "5444:5444"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data
        target: /data
      - type: bind
        source: initdb
        target: /docker-entrypoint-initdb.d/

  datagen:
    environment:
      DEMO_RUN_LENGTH: ${DEMO_RUN_LENGTH}
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  vertica-data:
